require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/medical_procedures", type: :request do

  before(:each) do
    admin_user = FactoryBot.create(:admin_user)
    user = FactoryBot.create(:user, email_address: admin_user.email)
    animal_type_dog = FactoryBot.create(:animal_type, name: 'собака', plural_name: 'собаки')
    sign_in(user)
  end
  
  # This should return the minimal set of attributes required to create a valid
  # MedicalProcedure. As you add validations to MedicalProcedure, be sure to
  # adjust the attributes here as well.
  let!(:animal) { FactoryBot.create(:animal) }
  let!(:procedure_type) { FactoryBot.create(:procedure_type) }
  let(:valid_attributes) {
    FactoryBot.attributes_for(:medical_procedure, animal_id: animal.id, procedure_type_id: procedure_type.id)
  }

  let(:invalid_attributes) {
    FactoryBot.attributes_for(:medical_procedure, animal_id: nil, procedure_type_id: procedure_type.id)
  }

  describe "GET /index" do
    it "renders a successful response" do
      MedicalProcedure.create! valid_attributes
      get medical_procedures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      medical_procedure = MedicalProcedure.create! valid_attributes
      get medical_procedure_url(medical_procedure)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_medical_procedure_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      medical_procedure = MedicalProcedure.create! valid_attributes
      get edit_medical_procedure_url(medical_procedure)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MedicalProcedure" do
        expect {
          post medical_procedures_url, params: { medical_procedure: valid_attributes }
        }.to change(MedicalProcedure, :count).by(1)
      end

      it "redirects to the created medical_procedure" do
        post medical_procedures_url, params: { medical_procedure: valid_attributes }
        expect(response).to redirect_to(medical_procedure_url(MedicalProcedure.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MedicalProcedure" do
        expect {
          post medical_procedures_url, params: { medical_procedure: invalid_attributes }
        }.to change(MedicalProcedure, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post medical_procedures_url, params: { medical_procedure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_animal) { FactoryBot.create(:animal, nickname: 'New Name', animal_type_id: animal.animal_type.id, animal_status_id: animal.animal_status_id ) }
      let(:new_attributes) {
        FactoryBot.attributes_for(:medical_procedure, animal_id: new_animal.id)
      }

      it "updates the requested medical_procedure" do
        medical_procedure = MedicalProcedure.create! valid_attributes
        patch medical_procedure_url(medical_procedure), params: { medical_procedure: new_attributes }
        medical_procedure.reload
        expect(medical_procedure.animal.nickname).to eq("New Name")
      end

      it "redirects to the medical_procedure" do
        medical_procedure = MedicalProcedure.create! valid_attributes
        patch medical_procedure_url(medical_procedure), params: { medical_procedure: new_attributes }
        medical_procedure.reload
        expect(response).to redirect_to(medical_procedure_url(medical_procedure))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        medical_procedure = MedicalProcedure.create! valid_attributes
        patch medical_procedure_url(medical_procedure), params: { medical_procedure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested medical_procedure" do
      medical_procedure = MedicalProcedure.create! valid_attributes
      expect {
        delete medical_procedure_url(medical_procedure)
      }.to change(MedicalProcedure, :count).by(-1)
    end

    it "redirects to the medical_procedures list" do
      medical_procedure = MedicalProcedure.create! valid_attributes
      delete medical_procedure_url(medical_procedure)
      expect(response).to redirect_to(medical_procedures_url)
    end
  end
end
